#!/usr/bin/env python3

import sys
import argparse
import os
import os.path as osp
import stat
import shlex
import shutil
import codecs
import collections

Inode = collections.namedtuple("Inode", ['size', 'mtime', 'files'])
Rankedfilename = collections.namedtuple("Rankedfilename", ['filename', 'rank'])

class Inodes(dict):
    __slots__ = ['rank', 'devicenum']

    def __init__(self):
        super(Inodes, self).__init__(self)
        self.devicenum = None
        self.rank = 0

    def discover(self, path):
        pdev = os.lstat(path).st_dev

        if not self.devicenum:
            self.devicenum = pdev
        if self.devicenum != pdev:
            raise ValueError("All paths should be on the same device.")

        for dirpath, dirnames, filenames in os.walk(path, followlinks=False):
            for dirname in dirnames[:]:
                if os.lstat(osp.join(dirpath, dirname)).st_dev != self.devicenum:
                    dirnames.remove(dirname)

            for filename in filenames:
                filepath = osp.join(dirpath, filename)
                fstat = os.lstat(filepath)
                dev = fstat.st_dev

                if not stat.S_ISREG(fstat.st_mode) or fstat.st_size == 0:
                    continue

                rfname = Rankedfilename(
                    filename = filepath,
                    rank = self.rank
                )
                if fstat.st_ino in self:
                    self[fstat.st_ino].files.append(rfname)
                else:
                    self[fstat.st_ino] = Inode(
                        size = fstat.st_size,
                        mtime = fstat.st_mtime,
                        files = [rfname]
                    )

        self.rank += 1

    def group_inodes_by_size(self):
        sizes = dict()
        for inum, inode in self.items():
            size = inode.size
            sset = sizes.setdefault(size, InodeSet([], self))
            sset.append(inum)
        return InodeSets(filter(lambda x: len(x)>1, sizes.values()), self)


class InodeSet(list):
    __slots__ = ['inodes', 'identical']
    InodeNameTup = collections.namedtuple("InodeNameTup", ['rank', 'depth', 'filename', 'inode', 'mtime'])

    def __init__(self, inode_set, inodes):
        super(InodeSet, self).__init__(inode_set)
        self.inodes = inodes
        self.identical = False

    def split_inode_set_by_range(self, start, bs):
        blockdict = dict()
        for inode in self:
            example_path = self.inodes[inode].files[0].filename
            with open(example_path, 'rb') as f:
                f.seek(start)
                blockdata = f.read(bs)
            new_inode_set = blockdict.setdefault(blockdata, InodeSet([], self.inodes))
            new_inode_set.append(inode)
        return InodeSets(filter(lambda x: len(x)>1, blockdict.values()), self.inodes)

    def print_inodes_info(self, **kwargs):
        example_inode = self[0]
        size = self.inodes[example_inode].size
        origname = self.sort_inode_names()[0].filename
        print(size, self, [self.inodes[inode].files for inode in self], origname, **kwargs)

    def sort_inode_names(self):
        names = []
        for inode in self:
            mtime = self.inodes[inode].mtime
            for rfname in self.inodes[inode].files:
                name = rfname.filename
                rank = rfname.rank
                depth = name.count(os.pathsep)
                names.append(self.InodeNameTup(rank, depth, name, inode, mtime))
        names.sort(key= lambda tup: (tup.rank, -tup.mtime, tup.depth))
        return names

    def do_dedup_inode(self):
        if not self.identical:
            raise ValueError()
        names = self.sort_inode_names()
        origname = names[0].filename
        for intup in names[1:]:
            name = intup.filename
            os.unlink(name)
            os.link(origname, name)

    def print_dedup_inode(self, **kwargs):
        if not self.identical:
            raise ValueError()
        names = self.sort_inode_names()
        origname = names[0].filename
        qorig = shlex.quote(origname)
        for intup in names[1:]:
            print('cp -la --remove-destination', qorig, shlex.quote(intup.filename), **kwargs)


class InodeSets(list):
    __slots__ = ['bs', 'inodes']

    def __init__(self, inode_sets, inodes):
        super(InodeSets, self).__init__(inode_sets)
        self.inodes = inodes
        self.bs = 2**20    # default 1 mebibyte block size

    def group_inodes_by_content(self):
        pos = 0 #start at zeroth block
        inode_sets = self
        while inode_sets:
            remaining_inode_sets = []
            start = pos*self.bs
            end = start+self.bs
            for input_inode_set in inode_sets:
                size = self.inodes[input_inode_set[0]].size
                new_inode_sets = input_inode_set.split_inode_set_by_range(start, self.bs)

                if size<=end:
                    for inode_set in new_inode_sets:
                        inode_set.identical = True
                        yield inode_set
                else:
                    remaining_inode_sets.extend(new_inode_sets)

            inode_sets = remaining_inode_sets
            pos += 1


def make_parser():
    parser = argparse.ArgumentParser(description="Deduplicate files")
    actions = parser.add_argument_group(title='Actions', description='At least one action should be performed')
    actions.add_argument('--make-hard-links',    action='store_true', help="Perform deduplication by making hard links")
    actions.add_argument('--print-dedup-script', action='store_true', help="Print shell script to perform deduplication later (to stdout)")
    actions.add_argument('--print-info',         action='store_true', help="Print info about the identified deduplication groups (to stderr)")
    parser.add_argument('dirs', metavar="DIR", nargs='+')
    return parser

def check_args(parser):
    args = parser.parse_args()

    if not any([args.make_hard_links, args.print_info, args.print_dedup_script]):
        parser.print_help()
        sys.exit(1)

    return args


def main(args):
    inodes = Inodes()
    for path in args.dirs:
        inodes.discover(path)

    inode_sets = inodes.group_inodes_by_size()

    for final_inode_set in inode_sets.group_inodes_by_content():
        if args.make_hard_links:
            final_inode_set.do_dedup_inode()
        if args.print_info:
            final_inode_set.print_inodes_info(file = sys.stderr)
        if args.print_dedup_script:
            final_inode_set.print_dedup_inode()


if __name__=="__main__":
    if sys.stdout.encoding.lower() == "utf-8":
        sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach(), errors='surrogateescape')
    if sys.stderr.encoding.lower() == "utf-8":
        sys.stderr = codecs.getwriter("utf-8")(sys.stderr.detach(), errors='surrogateescape')

    parser = make_parser()
    args = check_args(parser)
    main(args)
